defaults: &defaults
  docker:
    - image: circleci/node:12

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn build && yarn docs
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - package.json
            - LICENSE
            - README.md
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn ci
      - store_test_results:
          path: test_results

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
#      - run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
#      - run: npm publish
      - run:
          name: gh-pages
          command: |
            git init
            git config user.name leoshenhh
            git config user.email 343206898@qq.com
            git add -f dist/docs
            git commit -m 'update docs'
            git push -f https://${GH_TOKEN}@${GH_REF} master:gh-pages

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - prepare:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - prepare
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - test
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
#            branches:
#              ignore: /.*/
