defaults: &defaults
  docker:
    - image:circleci/node: 8

version: 2
jobs:
  prepare:
    <<: *defaults
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{checksum "package.json"}}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{checksum "package.json"}}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  test:
    <<: *defaults
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn ci
      - store_test_results:
          path: test_results
